---
# repo: jomrr/ansible-role-timesyncd
# file: handlers/main.yml

- name: "Restart systemd-timesyncd"
  become: true
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true
    masked: false
    state: restarted
