---
# role: ansible-role-systemd-timesyncd
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: systemd-timesyncd-alpine
    image: "jomrr/molecule-alpine:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: systemd-timesyncd-amazonlinux
    image: "jomrr/molecule-amazonlinux:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: systemd-timesyncd-arch
    image: "jomrr/molecule-archlinux:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: systemd-timesyncd-centos
    image: "jomrr/molecule-centos:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: systemd-timesyncd-debian
    image: "jomrr/molecule-debian:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: systemd-timesyncd-fedora
    image: "jomrr/molecule-fedora:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: systemd-timesyncd-opensuse
    image: "jomrr/molecule-opensuse:15"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: systemd-timesyncd-tumbleweed
    image: "jomrr/molecule-opensuse:tumbleweed"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: systemd-timesyncd-oraclelinux
    image: "jomrr/molecule-oraclelinux:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: systemd-timesyncd-ubuntu
    image: "jomrr/molecule-ubuntu:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        hosts_role_enabled: true
verifier:
  name: ansible
